name: Build Xiaomi AX3000T
on:
  label:
    types:
      - created
  schedule:
    - cron:  '19 3 * * 6'

jobs:
    build:
        name: Xiaomi AX3000T
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main
              with:
                repository: 'openwrt/openwrt'
                ref: 'master'
                
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                tool-cache: true
                android: true
                dotnet: true
                haskell: true
                large-packages: true
                docker-images: true
                swap-storage: true
                
            - name: Install Essential packages
              run: |
                sudo apt update -y && \
                sudo apt install -y \
                make git gcc g++ ack autoconf automake autopoint binutils bison \
                libncurses5-dev libncursesw5-dev build-essential bzip2 ccache cmake cpio \
                unzip bzip2 wget python3 file rsync gawk xz-utils curl device-tree-compiler \
                fastjar flex gettext gperf haveged help2man intltool libelf-dev libssl-dev \
                libtool lrzsz mkisofs nano ninja-build p7zip patch pkgconf wget vim xxd \
                software-properties-common

            - name: Install GoLang
              run: |
                sudo add-apt-repository ppa:longsleep/golang-backports && \
                sudo apt update && \
                sudo apt install -y golang-go
            
            - name: Update and install feeds
              run: |
                echo "src-git imm https://github.com/immortalwrt/packages" >> feeds.conf.default
                echo "src-git pw2 https://github.com/xiaorouji/openwrt-passwall2" >> feeds.conf.default
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for Xiaomi AX3000T
              run: |
                echo "CONFIG_TARGET_mediatek=y\n" > .config
                echo "CONFIG_TARGET_mediatek_filogic=y\n" >> .config
                echo "CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_mi-router-ax3000t=y\n" >> .config
                echo "CONFIG_PACKAGE_dnsmasq=m\n" >> .config
                echo "CONFIG_PACKAGE_dnsmasq-full=y\n" >> .config
                echo "CONFIG_PACKAGE_luci=y\n" >> .config
                echo "CONFIG_PACKAGE_luci-app-passwall2=y\n" >> .config

                make defconfig

            # - name: Download package sources
            #   run: make download -j$(nproc)

            # - name: Build tools
            #   run: |
            #     make tools/install -j$(nproc)

            # - name: Build toolchain
            #   run: |
            #     make toolchain/install -j$(nproc)

            - name: Build target images
              run: |
                make -j$(nproc)

            - name: TAR output
              run: tar -cvf filogicx-images.tar bin/targets/mediatek/filogic/

            - name: Upload artifacts
              uses: actions/upload-artifact@main
              with:
                name: filogic-images
                path: filogicx-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@main
              with:
                name: filogic-images

            - name: Extract the image artifacts
              run: tar xf filogicx-images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "Xiaomi AX3000T SNAPSHOT ${{ env.NOW }}"
                automatic_release_tag: "filogic-${{ env.NOW }}"
                auto_generate_release_notes: true
                files: bin/targets/mediatek/filogic/*
